import './assets/css/globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import Efeitos from './assets/components/efeitos'

export const metadata = {
  title: 'BD-Secretaria',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}
      <Efeitos/>
      </body>
    </html>
  )
}
